export type Language = {
  code: string;
  name: string;
  country?: string;
};

export const LANGUAGES: Language[] = [
  { code: "auto", name: "Auto Detect" },
  { code: "af", name: "Afrikaans", country: "za" },
  { code: "sq", name: "Albanian", country: "al" },
  { code: "am", name: "Amharic", country: "et" },
  { code: "ar", name: "Arabic", country: "sa" },
  { code: "hy", name: "Armenian", country: "am" },
  { code: "az", name: "Azerbaijani", country: "az" },
  { code: "eu", name: "Basque", country: "es" },
  { code: "be", name: "Belarusian", country: "by" },
  { code: "bn", name: "Bengali", country: "bd" },
  { code: "bs", name: "Bosnian", country: "ba" },
  { code: "bg", name: "Bulgarian", country: "bg" },
  { code: "ca", name: "Catalan", country: "es" },
  { code: "ceb", name: "Cebuano", country: "ph" },
  { code: "ny", name: "Chichewa", country: "mw" },
  { code: "zh-CN", name: "Chinese (Simplified)", country: "cn" },
  { code: "zh-TW", name: "Chinese (Traditional)", country: "tw" },
  { code: "co", name: "Corsican", country: "fr" },
  { code: "hr", name: "Croatian", country: "hr" },
  { code: "cs", name: "Czech", country: "cz" },
  { code: "da", name: "Danish", country: "dk" },
  { code: "nl", name: "Dutch", country: "nl" },
  { code: "en", name: "English", country: "gb" },
  { code: "eo", name: "Esperanto" },
  { code: "et", name: "Estonian", country: "ee" },
  { code: "tl", name: "Filipino", country: "ph" },
  { code: "fi", name: "Finnish", country: "fi" },
  { code: "fr", name: "French", country: "fr" },
  { code: "fy", name: "Frisian", country: "nl" },
  { code: "gl", name: "Galician", country: "es" },
  { code: "ka", name: "Georgian", country: "ge" },
  { code: "de", name: "German", country: "de" },
  { code: "el", name: "Greek", country: "gr" },
  { code: "gu", name: "Gujarati", country: "in" },
  { code: "ht", name: "Haitian Creole", country: "ht" },
  { code: "ha", name: "Hausa", country: "ng" },
  { code: "haw", name: "Hawaiian", country: "us" },
  { code: "he", name: "Hebrew", country: "il" },
  { code: "hi", name: "Hindi", country: "in" },
  { code: "hmn", name: "Hmong" },
  { code: "hu", name: "Hungarian", country: "hu" },
  { code: "is", name: "Icelandic", country: "is" },
  { code: "ig", name: "Igbo", country: "ng" },
  { code: "id", name: "Indonesian", country: "id" },
  { code: "ga", name: "Irish", country: "ie" },
  { code: "it", name: "Italian", country: "it" },
  { code: "ja", name: "Japanese", country: "jp" },
  { code: "jv", name: "Javanese", country: "id" },
  { code: "kn", name: "Kannada", country: "in" },
  { code: "kk", name: "Kazakh", country: "kz" },
  { code: "km", name: "Khmer", country: "kh" },
  { code: "ko", name: "Korean", country: "kr" },
  { code: "ku", name: "Kurdish", country: "iq" },
  { code: "ky", name: "Kyrgyz", country: "kg" },
  { code: "lo", name: "Lao", country: "la" },
  { code: "la", name: "Latin", country: "va" },
  { code: "lv", name: "Latvian", country: "lv" },
  { code: "lt", name: "Lithuanian", country: "lt" },
  { code: "lb", name: "Luxembourgish", country: "lu" },
  { code: "mk", name: "Macedonian", country: "mk" },
  { code: "mg", name: "Malagasy", country: "mg" },
  { code: "ms", name: "Malay", country: "my" },
  { code: "ml", name: "Malayalam", country: "in" },
  { code: "mt", name: "Maltese", country: "mt" },
  { code: "mi", name: "Maori", country: "nz" },
  { code: "mr", name: "Marathi", country: "in" },
  { code: "mn", name: "Mongolian", country: "mn" },
  { code: "my", name: "Myanmar", country: "mm" },
  { code: "ne", name: "Nepali", country: "np" },
  { code: "no", name: "Norwegian", country: "no" },
  { code: "or", name: "Odia", country: "in" },
  { code: "ps", name: "Pashto", country: "af" },
  { code: "fa", name: "Persian", country: "ir" },
  { code: "pl", name: "Polish", country: "pl" },
  { code: "pt", name: "Portuguese", country: "pt" },
  { code: "pa", name: "Punjabi", country: "in" },
  { code: "ro", name: "Romanian", country: "ro" },
  { code: "ru", name: "Russian", country: "ru" },
  { code: "sm", name: "Samoan", country: "ws" },
  { code: "gd", name: "Scots Gaelic", country: "gb-sct" },
  { code: "sr", name: "Serbian", country: "rs" },
  { code: "st", name: "Sesotho", country: "ls" },
  { code: "sn", name: "Shona", country: "zw" },
  { code: "sd", name: "Sindhi", country: "pk" },
  { code: "si", name: "Sinhala", country: "lk" },
  { code: "sk", name: "Slovak", country: "sk" },
  { code: "sl", name: "Slovenian", country: "si" },
  { code: "so", name: "Somali", country: "so" },
  { code: "es", name: "Spanish", country: "es" },
  { code: "su", name: "Sundanese", country: "id" },
  { code: "sw", name: "Swahili", country: "ke" },
  { code: "sv", name: "Swedish", country: "se" },
  { code: "tg", name: "Tajik", country: "tj" },
  { code: "ta", name: "Tamil", country: "in" },
  { code: "te", name: "Telugu", country: "in" },
  { code: "th", name: "Thai", country: "th" },
  { code: "tr", name: "Turkish", country: "tr" },
  { code: "uk", name: "Ukrainian", country: "ua" },
  { code: "ur", name: "Urdu", country: "pk" },
  { code: "ug", name: "Uyghur", country: "cn" },
  { code: "uz", name: "Uzbek", country: "uz" },
  { code: "vi", name: "Vietnamese", country: "vn" },
  { code: "cy", name: "Welsh", country: "gb-wls" },
  { code: "xh", name: "Xhosa", country: "za" },
  { code: "yi", name: "Yiddish", country: "il" },
  { code: "yo", name: "Yoruba", country: "ng" },
  { code: "zu", name: "Zulu", country: "za" },
];

export const LANGUAGE_MAP: Record<string, Language> = LANGUAGES.reduce(
  (acc, lang) => {
    acc[lang.code] = lang;
    return acc;
  },
  {} as Record<string, Language>,
);

export function findLanguage(code: string): Language | undefined {
  return LANGUAGE_MAP[code];
}
